### ISSUE TITLE
IBM XLC++ 13.1 issue

### ISSUE THREAD

**Issue by takiguc** [AdoptOpenJDK/openjdk-jdk11#9] opened 2018-11-30 13:11 UTC
About following change for src/java.base/share/native/libjimage/NativeImageBuffer.cpp
https://github.com/AdoptOpenJDK/openjdk-jdk11/commit/2c42c24ca03bc1f6f33d6cdc8f8186fc9ca81bad

I think that actual issue is in IBM XLC++ 13.1.
Please open support request against IBM XLC++ 13.1.

Thanks.

**Comment by karianna** [comment] 2018-11-30 18:22
@sxa555 I'll let you tackle this but IIRC this has already been fixed upstream?

**Comment by sxa** [comment] 2018-12-06 13:23
@adamfarley Is this the one you're pushing back to openjdk?

**Comment by adamfarley** [comment] 2018-12-06 15:35
It's the same bug, yes.

It's caused by the use of the -qvisibility issue on the xlC_r command line, and it's resolved in the head/jdk12 branch of openjdk by the removal of that option.

http://hg.openjdk.java.net/jdk/jdk/rev/fc54d27e58d8

Also, I reached out to the xlc development folk, but they were reluctant to get involved without a minimal testcase. 

Lastly, the OpenJDK group has another bug open to re-introduce the option while handling resultant issues like exported variables: https://bugs.openjdk.java.net/browse/JDK-8204541

**Comment by adamfarley** [comment] 2018-12-07 10:57
We now have a minimal test case. Credit to @takiguc for producing it.

I'll pass the code onwards. Will update here when we have a response from the xlc people.

**Comment by karianna** [comment] 2019-01-16 23:25
@adamfarley Does this issue need to be closed/transferred?

**Comment by adamfarley** [comment] 2019-01-17 10:06
A "support request" has been opened, but I have not heard back.

If you're including "and then ride the issue to completion" in the scope of this issue, then it needs to stay open until they respond. If so, I can send an email to follow up.

If not, then we can close this.

**Closed as completed** 2019-01-17 13:57 UTC
Labels: bug, Reported Upstream
